In [30]:
import numpy as np
import cv2
import glob
import os

In [31]:
# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
left_imgpoints = [] # 2d points in image plane.
right_imgpoints = [] # 2d points in image plane.

left_images = glob.glob('../img/left/*.jpg')
right_images = glob.glob('../img/right/*.jpg')

for left_fname, right_fname in zip(left_images, right_images):
    left_img = cv2.imread(left_fname)
    right_img = cv2.imread(right_fname)
    left_gray = cv2.cvtColor(left_img,cv2.COLOR_BGR2GRAY)
    right_gray = cv2.cvtColor(right_img,cv2.COLOR_BGR2GRAY)
    left_ret, left_corners = cv2.findChessboardCorners(left_gray, (7,6), None)
    right_ret, right_corners = cv2.findChessboardCorners(right_gray, (7,6), None)
    if left_ret and right_ret:
        objpoints.append(objp)
        cv2.cornerSubPix(left_gray, left_corners, (11,11), (-1,-1), criteria)
        cv2.cornerSubPix(right_gray, right_corners, (11,11), (-1,-1), criteria)
        left_imgpoints.append(left_corners)
        right_imgpoints.append(right_corners)
        
ret1, mtx1, dist1, rvecs1, tvecs1 = cv2.calibrateCamera(objpoints, left_imgpoints, left_gray.shape[::-1], None, None)
ret2, mtx2, dist2, rvecs2, tvecs2 = cv2.calibrateCamera(objpoints, right_imgpoints, left_gray.shape[::-1], None, None)

In [32]:
retv, mtx1, dist1, mtx2, dist2, R, T, E, F = \
cv2.stereoCalibrate(objpoints, left_imgpoints, right_imgpoints, mtx1, dist1, mtx2, dist2, left_gray.shape[::-1], criteria)

In [33]:
mtx1

array([[ 535.04584846,    0.        ,  341.29707287],
       [   0.        ,  535.34171797,  233.71686258],
       [   0.        ,    0.        ,    1.        ]])

In [19]:
dist1

array([[ -2.94287880e-01,   1.07251583e-01,   1.47206922e-03,
          2.29315345e-04,   5.38660840e-02]])

In [20]:
mtx2

array([[ 538.13540769,    0.        ,  326.09424291],
       [   0.        ,  537.66198584,  247.87749169],
       [   0.        ,    0.        ,    1.        ]])

In [21]:
dist2

array([[ -3.01741568e-01,   2.07774829e-01,  -2.57939547e-05,
          1.10971971e-03,  -1.90194386e-01]])

In [22]:
R

array([[ 0.48989772,  0.36939739,  0.78964916],
       [ 0.07713897,  0.88386877, -0.46133022],
       [-0.86836041,  0.28691735,  0.40451036]])

In [23]:
T

array([[-12.73694515],
       [  5.27754566],
       [  8.81414828]])

In [24]:
E

array([[ -5.26272606,  -6.276331  ,   6.20105488],
       [ -6.74222778,   6.91037388,  12.11231105],
       [ -3.56797245, -13.20729964,   1.70852824]])

In [25]:
F

array([[  4.71339795e-06,   5.61809520e-06,  -5.89324113e-03],
       [  6.04378493e-06,  -6.19108884e-06,  -6.42506143e-03],
       [ -1.31549467e-03,   6.06453259e-03,   1.00000000e+00]])